version: '3.3'

services:
  pylora:
    build: .
    restart: unless-stopped
    volumes:
      - /proc/:/proc/
      - /dev/:/dev/
      - /sys/:/sys/
    privileged: true
  ouroboros:
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - SELF_UPDATE=true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
